### ISSUE TITLE
Dialog: 0.4.0-1 dialog left and right panel scroll is broken in mweb

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#174] opened 2018-05-14 22:14 UTC
## How to reproduce
1. create a left or right panel dialog with content to scroll
1. open the page on an IOS device
1. open the dialog and scroll

## expected
![image](https://user-images.githubusercontent.com/13157115/40026319-c3e507c0-5789-11e8-9259-1b8003809791.png)

## actual
![image](https://user-images.githubusercontent.com/13157115/40026232-66156b4e-5789-11e8-9e70-cd282e60eddb.png)

**Comment by ianmcburnie** [comment] 2018-05-14 22:16
@hramakumar is this a regression since 0.3.0?

**Comment by hramakumar** [comment] 2018-05-14 22:16
**expected:**
![image](https://user-images.githubusercontent.com/13157115/40026319-c3e507c0-5789-11e8-9259-1b8003809791.png)

**Comment by ianmcburnie** [comment] 2018-05-15 15:46
@DylanPiercey Can you please take a look?

**Comment by ianmcburnie** [comment] 2018-06-07 20:02
This was fixed in 0.4.0.

**Closed by ianmcburnie** 2018-06-07 20:02 UTC
Labels: component: dialog, sprint: 8, type: bug
