### ISSUE TITLE
ebay-combobox: copy & paste doesn’t fire the combobox-input

### ISSUE THREAD

**Issue by malughanshyam** [eBay/ebayui-core#1098] opened 2020-04-16 23:53 UTC
**Version**
`"@ebay/ebayui-core": "^4.5.0"`

**Issue**
After pasting the content, pressing “enter” doesn’t fire the `combobox-input` event.
Is there a way to know when the user has pressed enter so that we can take action?
No event is fired even on “`blur`” or `combobox-change` after pasting text in the text box.

IAN EDIT: the following requests should be moved to separate tickets.

**Request - 0** 
Can you support "error" attribute/state so that we don't have to hack through the borders to make it red? 

**Request - 1** 
Is there a way to disable the browser's autocomplete feature when we already use the autocomplete of the component. It annoys to see 2 dropdowns at the same time. 
![image](https://user-images.githubusercontent.com/5460329/79517183-4d191200-8002-11ea-90c7-03a420e3efd7.png)
![image](https://user-images.githubusercontent.com/5460329/79536524-19a3ab00-8035-11ea-9dd0-009327500185.png)

**Request - 2** 
Can you support "`max-len`" attribute? 

**Request - 3** 
Can you support an attribute to achieve a wider combobox?

**Comment by ianmcburnie** [comment] 2020-04-20 23:29
0 you can set `aria-inavlid="true"`
1 is a known issue #819 
2 you can set the `maxlength` attribute directly
3 you should use CSS

If will repurpose this ticket for the copy and paste issue (also see related: https://github.com/eBay/ebayui-core/issues/648)

**Comment by ianmcburnie** [comment] 2020-05-05 22:58
@malughanshyam can you please update us on the status of your requests. Please see my previous comment.

**Comment by malughanshyam** [comment] 2020-05-08 19:36
Hello @ianmcburnie , 
We had to go with ebay-select temporarily. But we will re-start the development using the ebay-combobox. 
Also, is there a way we can pin an element/option to the top of the list within the dropdown of combobox?
Like a sticky default option that would stay at the top?

**Comment by ianmcburnie** [comment] 2020-05-08 19:58
@malughanshyam Assuming you are talking about the autosuggest version of combobox, I don't think there's a way to do that currently. Feel free to create an issue with this feature request and we can consider it for a future release. It should be fine given that there are no hard and fast rules about how auto suggest options should be ordered/proritized.

**Comment by malughanshyam** [comment] 2020-05-08 21:38
Thanks Ian. Created a feature request https://github.com/eBay/ebayui-core/issues/1116

**Comment by ianmcburnie** [comment] 2020-06-17 02:12
Closing this as a dupe of https://github.com/eBay/ebayui-core/issues/648

**Closed by ianmcburnie** 2020-06-17 02:12 UTC
Labels: component: combobox, type: bug
