### ISSUE TITLE
Select: Nexus 10: android tablet - clicking on the component again does not close the options list

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#232] opened 2018-06-29 00:42 UTC
# Bug Report

## Description
Android tablet Nexus 10 Safari and chrome
https://go/ebayui/test
click on ebay-select and expand the options list
now click on the top of the component to collapse it
It collapses and then opens again

**Comment by ianmcburnie** [comment] 2018-06-29 19:22
Assigning to @seangates for investigation/scoping only.

**Comment by yomed** [comment] 2018-07-03 20:49
@seangates Did you end up looking into this one at all? I reproduced this issue on a virtual Nexus 10 through Android Studio, and this looks like expected browser behavior. I see the exact same behavior in interacting with basic `<select>` tags.

**Comment by seangates** [comment] 2018-07-03 21:17
I have not looked at this. I would actually welcome help setting up Android Studio. It was difficult for me to set up and use in the past.

**Comment by yomed** [comment] 2018-07-03 21:33
@hramakumar Closing, as this is default browser/device behavior.

**Closed by yomed** 2018-07-03 21:33 UTC
Labels: component: select, severity: non-blocker, sprint: 11, status: investigation, type: bug, workaround: yes

**Comment by hramakumar** [comment] 2018-07-03 21:36
ok
