### ISSUE TITLE
[ebay-infotip]: Variant 'modal' layout issue on close button

### ISSUE THREAD

**Issue by HenriqueLimas** [eBay/ebayui-core#1949] opened 2023-07-26 22:59 UTC
# Bug Report

## Description

Use ebay-infotip with variant `modal` ([storybook](https://opensource.ebay.com/ebayui-core/?path=/story/buttons-ebay-infotip--default&args=variant:modal))

The close button of the drawer dialog is rendering incorrectly.

The reason is that the `.drawer-dialog` is being rendered as a child of `.infotip` and there is a `.infotip .icon-btn` that impacts in the rendering. The `.drawer-dialog` should be rendered as a sibling of `.infotip` the same as [skin version](https://opensource.ebay.com/skin/#infotip).

## Screenshots

<img width="532" alt="Screen Shot 2023-07-26 at 3 43 34 PM" src="https://github.com/eBay/ebayui-core/assets/2222191/041b291c-5603-4445-baf7-2f5abc338305">

**Comment by agliga** [comment] 2023-10-10 14:36
Closing issue
Drawer dialog is deprecated. Will switch it over to lightbox dialog.

**Closed by agliga** 2023-10-10 14:36 UTC

**Comment by agliga** [comment] 2023-10-10 14:45
Actually, the issue is present in lightbox. This is a skin problem. Will open an issue on skin.
