### ISSUE TITLE
ebay-infotip: Clicking anywhere in the page doesn't close the overlay and Overlay doesn't align to the page as we resize the browser

### ISSUE THREAD

**Issue by udaya888** [eBay/ebayui-core#1478] opened 2021-07-27 04:16 UTC
### eBayUI Version: 7.1.0
**Description**

- Clicking anywhere in the page doesn't close the overlay. We have to click either on icon link or click on the Close button. 
- Overlay doesn't align to the page as we resize the browser. Overlay is always static to the page.

**Screenshots**
**Clicking anywhere in the page doesn't close the overlay** (please review overlay on view item page)

![image](https://user-images.githubusercontent.com/8204473/127094049-6d231cb9-80ee-45e8-98e0-60beb8066282.png)

**Overlay doesn't align to the page as we resize the browser** (please review overlay on view item page)

![image](https://user-images.githubusercontent.com/8204473/127094091-55c0358b-ec10-435e-a863-4e1e97219158.png)

**Comment by ianmcburnie** [comment] 2021-07-27 14:44
"Clicking anywhere in the page doesn't close the overlay. We have to click either on icon link or click on the Close button."

This is by design. Wont fix. If there is a special need for your app to close an infotip in this manner you can do it via the components state.

"Overlay doesn't align to the page as we resize the browser. Overlay is always static to the page."

This is a known issue that is on our backlog: https://github.com/eBay/ebayui-core/issues/535. It is also solvable at the app level if necessary.

Closing.

**Closed by ianmcburnie** 2021-07-27 14:44 UTC
