### ISSUE TITLE
Combobox does not seam to follow ARIA recommendation for keyboard interaction

### ISSUE THREAD

**Issue by cc-ebay** [eBay/ebayui-core#1783] opened 2022-10-06 01:23 UTC
# Bug Report

## Description
I was looking at the [Combobox Keyboard Interaction described in WAI-ARIA](https://w3c.github.io/aria-practices/#keyboard-interaction-6). It looks like that the `ebay-combobox` is not compliant in a few cases (ex: arrow up and arrow down).

**Comment by ianmcburnie** [comment] 2022-10-06 03:40
What isn't compliant about the current arrow up and down behavior? Can you please be more specific.

Also, you have linked to an editors draft of ARIA 1.2. Was this intentional? Our combobox follows ARIA 1.0.

**Comment by cc-ebay** [comment] 2022-10-06 19:28
I noticed some behaviors that were a "little surprising" when I was interacting with the keyboard.
I was looking at alternative combobox implementations and eventually I found this.

Do you have a link to the ARIA 1.0 combobox? Does it have something like the "Combobox Keyboard Interaction" here?

**Comment by ianmcburnie** [comment] 2022-10-06 20:59
What behaviours were surprising with keyboard? Please elaborate what the issue is and then we might be able to help.

**Comment by cc-ebay** [comment] 2022-10-07 00:28
I have been trying to implement a listbox with "search" capability that it is accessible.
It looked like that a combobox with autocomplete may have been the way to go.

As I was trying to use it I found two bugs (#1782 and #1771) and regarding ARIA, you are saying here that `ebay-combobox` is supposed to follow ARIA 1.0 where the [ARIA document](https://w3c.github.io/aria/#combobox) says:

>EDITOR'S NOTE: Major Changes to combobox role in ARIA 1.2
> The Guidance for [combobox](https://w3c.github.io/aria/#combobox) has changed significantly in ARIA 1.2 **due to problems with implementation of the previous patterns**. Authors and developers of User Agents, Assistive Technologies, and Conformance Checkers are advised to review this section carefully to understand the changes. Explanation of the changes is available in the [ARIA repository wiki](https://github.com/w3c/aria/wiki/Resolving-ARIA-1.1-Combobox-Issues).

And in the wiki:

> ... on the screen, the textbox input and listbox popup are two separate things. So, the accessibility tree for an ARIA 1.0 combobox does not accurately represent the semantics of the user interface.
> This creates problems for screen reader users when using reading or touch modes. They cannot perceive a popup inside of an edit field. The popup is simply not present in the reading order. 

Because of that, it seems futile trying to implement an accessible combobox with ARIA 1.0 specs.

I thought that using this component was going to help me to avoid accessibility bugs, helping to move faster and being a reusable approach but so far the results have been very discouraging and I am thinking that using a completely new component is going to be a better choice.

**Comment by agliga** [comment] 2022-10-07 00:38
I see that Ian has asked twice what the actual keyboard issue is and that we have not gotten an answer yet. 
So I will ask, what is the issue? I read this bug over and over and I don't see the specific keyboard issue in this bug other than those two bugs you found (which are both being addressed or will be addressed). 

These kind of discussions are actually a large waste of time. If you have a specific issue all you have to do is file a bug with the issue at hand and we will get to it. That's it. If we don't get to it, there's probably a reason (timing, priorities, roadmaps, not a bug etc).

If there is something you are unhappy about or you don't like our opinion on these things, go ahead and setup some time to discuss with us. 

But these back and forth's are not getting us anywhere.

**Comment by ianmcburnie** [comment] 2022-10-07 02:09
Quick summary of ARIA combobox history:

- ARIA 1.0 had some problems for screen reader users (as described in your snippet above)
- ARIA 1.1 tried to address those problems by adopting a different structure, but ended up making it worse
- ARIA 1.2 tries to fix it again (and will hopefully be succesful), largely by reverting to the ARIA 1.0 structure, but is NOT yet well supported across browsers and AT

When it is the right time to move to ARIA 1.2 we will do so. That time will be when the spec is supported well enough across our Tier 1 browsers and AT.

It is certainly not "futile" to use ARIA 1.0 combobox, despite what a quick google search may make you think. It has some short comings but remains the best option for now. What you are running into is mostly likely just a bug in our code. It has nothing to do with which spec we are following. You would only run into the issue with ARIA 1.0 if you were using a screenreader. It doesn't sound like you are. Like any kind of bug, this will be looked at and fixed. But first, you have to tell us what the bug is.

We have a core accessibility team with many, many years of combined experience. The job doesn't just entail doing a quick google search to get the answer. It involves much, much more than that. Using this component WILL most certainly help you avoid the vast majority of accessibility bugs that developers run into when trying to build a combobox.

**Comment by cc-ebay** [comment] 2022-10-07 20:34
Probably part of the issue here is my lack of experience with ARIA comboboxes.
It started when I noticed that my interaction with `ebay-combobox` did not feel intuitive. I wondered if it was just me or it was not working as expected. I looked up how a combobox was supposed to work in ARIA and it looked like it was not following [Combobox Keyboard Interaction described in WAI-ARIA](https://w3c.github.io/aria-practices/#keyboard-interaction-6). Then @ianmcburnie pointed out that I referenced the ARIA 1.2 and the code was made for 1.0. **At that point the conversion deviated from what was in the title**.

Coming to the less than ideal interaction I experienced, I think most of the problems are side effects of https://github.com/eBay/ebayui-core/issues/1782 and the long list of options I was using (see the code in  https://github.com/eBay/ebayui-core/issues/1782).

These are the problems I still notice with the example in the playbook on `master`:
- Normally when the text is focus and an option is selected and the dropdown is close, arrow up open the drop down and move on the next option up. Arrow down open the drop down and move on the next option down. BUT if it the option was selected with the mouse this behavior does not work. It seems that when an item is selected with the mouse the control loses focus.
- If you add a Space at the end of the input the dropdown is still open and unfiltered even if no option match a text with the extra trailing Space.

All the "optional" things in the [Combobox Keyboard Interaction described in WAI-ARIA](https://w3c.github.io/aria-practices/#keyboard-interaction-6) are not implemented. I think if implemented they would add a lot to the experience. Especially if the first option is selected and arrow up is pressed, the last option is selected. This will reduce 1/2 the average time to select an option. It is particularly useful when the list of options is long.

**Comment by agliga** [comment] 2022-10-19 22:14
Closing issue since we resolved the other two issues, and I don't see any ask in this issue. 

I don't see anything here we either: plan on doing, or will do in the near future.

If we do decide to implement the new ARIA 1.2 when it is streamlined we will open individual issues to track those changes.

**Closed by agliga** 2022-10-19 22:14 UTC
Labels: blocked: discussion
