### ISSUE TITLE
combobox: visually highlighted option state sometimes remains after collapsing/expanding

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#781] opened 2019-07-24 19:39 UTC
# Bug Report

## eBayUI Version: 2.8.0-4 and older version
when I select an option by typing on part of the text and the click on the option from the list.
the next time when I open up the combobox the option is not highlighted.
Highlighting happens only when I enter the entire text and the select the option

## Screenshots
https://www.loom.com/share/843e531101c74ba78234a2cfbac1541f

**Comment by ianmcburnie** [comment] 2019-07-24 20:11
This is working as intended. Combobox options do not have any kind of state other than hover.

Closing as invalid.

**Comment by hramakumar** [comment] 2019-07-24 23:11
discussed with Ian.
We need to remove the highlighting of the text when I type the entire option text and select an option.
When I blurr out and then click the combobox with the selected option. It expands with the option highlighted.
Its a low priority issue.

**Comment by ianmcburnie** [comment] 2020-01-03 22:32
It's low priority, and a bit of an edge case. I'm going to close so we can focus on higher priorities.

**Closed by ianmcburnie** 2020-01-03 22:32 UTC
Labels: component: combobox, priority: 3, regression: no, resolution: won't fix, severity: non-blocker, type: bug
