### ISSUE TITLE
Menu: Support expand-btn--no-text

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/ebayui-core#383] opened 2018-08-27 21:34 UTC
# Feature Request

## Description
Support menu with no label. Relevant details [here](https://github.com/eBay/skin/pull/333)

**Comment by yomed** [comment] 2018-08-27 23:05
Duplicate of #382 created about 2 minutes beforehand 😆

**Closed by yomed** 2018-08-27 23:05 UTC
