### ISSUE TITLE
Video:  Value of volume control can be set only as 0% or 100%

### ISSUE THREAD

**Issue by shanelin1** [eBay/ebayui-core#1436] opened 2021-07-07 17:17 UTC
# Bug Report

## Description
1. Using TalkBack + Chrome,
2. swipe to play video, Once the video starts to play, swipe to focus the volume slider control.
3. Try to change the value by swiping up or down.

Expected Result
The user should be able to select any slider value by swiping up/down.

Actual Result
The user is able to select only 0% or 100% value but nothing between.

**Comment by agliga** [comment] 2021-07-07 19:03
I am able to swipe on storybook and see that the slider changes `0.01` every time I swipe and change it. 
Could this be related to the change volume event possibly? @shanelin1 

https://user-images.githubusercontent.com/1755269/124814788-49312280-df1b-11eb-98b7-19dd3458d5af.mov

**Comment by shanelin1** [comment] 2021-07-07 22:21
Should not be the case, because they already started test when I was trying to integrate the new player.


From: Andrew Gliga ***@***.***>
Reply-To: eBay/ebayui-core ***@***.***>
Date: Wednesday, July 7, 2021 at 12:04 PM
To: eBay/ebayui-core ***@***.***>
Cc: "Lin, Shane" ***@***.***>, Mention ***@***.***>
Subject: Re: [eBay/ebayui-core] Videos - Value of volume control can be set only as 0% or 100% (#1436)

External Email

I am able to swipe on storybook and see that the slider changes 0.01 every time I swipe and change it.
Could this be related to the change volume event possibly? @shanelin1<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshanelin1&data=04%7C01%7Cshalin%40ebay.com%7Cf1ccc8b302834920d00b08d9417a1254%7C46326bff992841a0baca17c16c94ea99%7C0%7C0%7C637612814818920722%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RR1qzMUTzAs4vAqUfHB8R5YVZcLDOmvEdZBn0UExbf4%3D&reserved=0>

https://user-images.githubusercontent.com/1755269/124814788-49312280-df1b-11eb-98b7-19dd3458d5af.mov<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1755269%2F124814788-49312280-df1b-11eb-98b7-19dd3458d5af.mov&data=04%7C01%7Cshalin%40ebay.com%7Cf1ccc8b302834920d00b08d9417a1254%7C46326bff992841a0baca17c16c94ea99%7C0%7C0%7C637612814818930679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oSvLVSL65P2TUhwecbFiBTxPNpsc7u1CytejjhFesVA%3D&reserved=0>

**Comment by agliga** [comment] 2021-07-07 22:45
I would compare with storybook and see what the difference is. 
Can you test on storybook and see if this is reproducible. I cannot seem to reproduce it
If so then this could be an issue with the integration and the container it is in.

**Comment by shanelin1** [comment] 2021-07-08 00:00
I can reproduce the issue on playbook on an Android real device.


From: Andrew Gliga ***@***.***>
Reply-To: eBay/ebayui-core ***@***.***>
Date: Wednesday, July 7, 2021 at 3:46 PM
To: eBay/ebayui-core ***@***.***>
Cc: "Lin, Shane" ***@***.***>, Mention ***@***.***>
Subject: Re: [eBay/ebayui-core] Videos - Value of volume control can be set only as 0% or 100% (#1436)

External Email

I would compare with storybook and see what the difference is.
Can you test on storybook and see if this is reproducible. I cannot seem to reproduce it
If so then this could be an issue with the integration and the container it is in.

**Comment by ianmcburnie** [comment] 2021-07-14 23:49
Related to: https://github.com/eBay/ebayui-core/issues/1435

Suggestion from Lauren is to hide volume sliders on mweb. Device's volume buttons can be used.

The app is responsible for device detection and then disabling ebayui player's volume control via our API.

**Comment by ianmcburnie** [comment] 2021-07-16 16:34
Closing due to #1463

**Closed by ianmcburnie** 2021-07-16 16:34 UTC
Labels: component: video
