### ISSUE TITLE
Badge inside menu item is broken

### ISSUE THREAD

**Issue by ushrivastava123** [eBay/ebayui-core#1039] opened 2020-01-29 09:42 UTC
# Bug Report
Badge inside menu item is broken

## eBayUI Version: 5.0.0-0

`<div id="badge_2" class="grid__cell grid__cell--4of16 grid__cell--4of16-lg grid__cell--4of8-sm" draggable="true" ondragstart="drag(event)">
                    <h3>badge in menu item</h3>
                    <ebay-menu-button text="eBay Menu">
                        <ebay-menu-button-item badge-number="5" aria-label="item 1 (5 unread items)">item 1</ebay-menu-button-item>
                        <ebay-menu-button-item badge-number="23" aria-label="item 2 (23 unread items)">item 2</ebay-menu-button-item>
                        <ebay-menu-button-item>item 3</ebay-menu-button-item>
                    </ebay-menu-button>
                </div>`

## Screenshots
Before:
![image](https://user-images.githubusercontent.com/57548118/73345260-a316be80-4238-11ea-9381-e06b518bf241.png)

After:
![image](https://user-images.githubusercontent.com/57548118/73345241-95613900-4238-11ea-8089-cd7858fa9abf.png)

**Comment by ushrivastava123** [comment] 2020-02-05 07:59
@agliga Menu item badge layout is still not fixed in 5.0.0-5

**Comment by agliga** [comment] 2020-02-05 16:15
I think i figured it out. The badge from the element after the menu is showing through the menu. Prob a zindex issue.  
I doubt that there will be cases where there is a badge underneath a menu. And that it will show through. 
I don’t think this is a showstopper.

**Comment by ianmcburnie** [comment] 2020-02-05 16:19
Agreed.

**Comment by agliga** [comment] 2020-02-05 17:16
Just some more info on this.

This is caused by conflicting `z-index`. 
The item below the menu is the badge on top of an icon. Looking at the code it seems to be
https://github.com/eBay/skin/blob/10.0.0/src/less/actionable/base/actionable.less#L67
Which has a `z-index` of 1
The menu also has a `z-index` of 1. 
https://github.com/eBay/skin/blob/10.0.0/dist/mixins/dropdown/base/dropdown-mixins.less#L12

Removing the `z-index`in the actionable seems to be working but I don't know what other issues will be caused by this.

Screenshots for examples:
Normal test page with menu closed
![image](https://user-images.githubusercontent.com/1755269/73865138-aa6d3780-47f7-11ea-909a-085d10bac655.png)

Normal test page with menu opened
![image](https://user-images.githubusercontent.com/1755269/73865159-b0fbaf00-47f7-11ea-8254-9663d9eb4a4a.png)

Removed z-index on actionable menu closed
![image](https://user-images.githubusercontent.com/1755269/73865468-249dbc00-47f8-11ea-8522-38cf35515fdd.png)

Removed z-index on actionable menu open
![image](https://user-images.githubusercontent.com/1755269/73865475-29627000-47f8-11ea-95cf-b57f47e4723b.png)

Or we can increase menu z-index to 2 which also works.

**Comment by agliga** [comment] 2020-02-07 17:23
Fixed in `5.0.0`

**Closed** 2020-02-07 17:23 UTC
Labels: priority: 2, status: merged, status: qa, type: bug
