### ISSUE TITLE
Carousel: autoplay does not work (IE11, Edge)

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#743] opened 2019-07-08 19:06 UTC
# Bug Report

## Description
autoplay carousel does not work as intended.
The carousal auto slide and clicking on pause and play button wont work.

**Comment by agliga** [comment] 2019-09-10 21:01
I tried this on `4.1.0` branch  with edge I was able to see the autoplay work correctly.

**Comment by ianmcburnie** [comment] 2019-09-20 18:21
@hramakumar To verify as part of 4.2.0

**Comment by hramakumar** [comment] 2019-09-23 22:06
The issue still exists.
The autoplay carousal does not work in IE edge, windows 10

**Comment by agliga** [comment] 2019-09-23 22:52
Can you also provide a screenshare of the issue?

**Comment by hramakumar** [comment] 2019-09-25 23:20
![image](https://user-images.githubusercontent.com/13157115/65646588-5bdda000-dfb0-11e9-822b-3e6594d93892.png)

**Comment by hramakumar** [comment] 2019-09-25 23:21
it just stays still when i pause and pay. It does not move slides.
also I see that the paddles dont work

**Comment by ianmcburnie** [comment] 2019-09-26 02:00
Okay. Let's try and squeeze a fix into 4.2.0-1

**Comment by seangates** [comment] 2019-09-27 16:54
@hramakumar As with @agliga's assessment, I can't reproduce the issue either. Closing for now, and you can open a new issue with more information, if you see it not working again.

FWIW, I tested both your published site (ebayuicomponentstestenv.vip.qa.ebay.com) and pulled the test site code and ran it locally. Both had the same result that I could use the carousel as intended.

**Closed by seangates** 2019-09-27 16:54 UTC
Labels: aspect: IE11, component: carousel, priority: 3, regression: no, severity: non-blocker, status: closed, type: bug

**Comment by hramakumar** [comment] 2019-09-27 17:28
@seangates  did you try it in edge?  I know ie 11 works fine now
