### ISSUE TITLE
ebay-select: options does not look like button type anymore

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#225] opened 2018-06-28 04:41 UTC
# Bug Report

## Description
the ebay-select option does not look like button type anymore. It looks like a regular combobox
pls check the look in the screenshot and let me know if this is a bug or not

## Screenshots

![image](https://user-images.githubusercontent.com/13157115/42013521-8badf8c6-7a52-11e8-9b5c-066a36e871ff.png)

**Comment by seangates** [comment] 2018-06-28 04:45
Yeah, it's not supposed to, because it's now a native select. You'll need to add `ebay-combobox` to your tests, and you'll see the difference between the two.

**Comment by seangates** [comment] 2018-06-28 04:46
Therefore, it's not a bug. I'll close this. 👍

**Closed by seangates** 2018-06-28 04:46 UTC
Labels: component: select
