### ISSUE TITLE
ebay-carousel: Previous and Next buttons not getting disabled properly when state is used in the component

### ISSUE THREAD

**Issue by okannivadikubendran** [eBay/ebayui-core#1441] opened 2021-07-07 17:29 UTC
# Bug Report

## Description
We are seeing the following issue after using `state` in `next` or `previous` event handlers of the `ebay-carousel` component.  Previous and Next buttons are getting disabled when they are not supposed to be.

```
class {
    onCreate() {
        this.state = {
            isNextClicked: false,
            isPreviousClicked: false,
            isScrolled: false,
            carouselIndex: 0
        };
    }

    handlePrevious() {
        if (!this.state.isPreviousClicked) {
            this.state.isPreviousClicked = true;
        }
    }

    handleNext() {
        if (!this.state.isNextClicked) {
            this.state.isNextClicked = true;
        }
    }

    handleScroll({ index }) {
        if (!this.state.isScrolled) {
            this.state.isScrolled = true;
            this.state.carouselIndex = index;
        }
    }
};

<ebay-carousel
            on-previous('handlePrevious')
            on-next('handleNext')
            on-scroll('handleScroll')
            on-move('handleMove')
            index=state.carouselIndex>
....
</ebay-carousel>
```

## Suggested fixes

Both of these fixes work fine only  if the `state` is not set in `handlePrevious` and `handleNext` functions but state is set only in `handleScroll`.

### Fix 1:
```
class {
  onCreate() {
    this.state = { index: 0 };
  }
  handleMove({ visibleIndexes: [index] }) {
    // Carousel moved, sync our index state.
    this.state.index = index;
  }
}
<ebay-carousel index=state.index on-move("handleMove")>
  ...
</>
```

### Fix 2:
```
class {
    onCreate() {
        this.state = {
            update: false,
            index: 0
        }
    }
    onScroll({index}) {
        this.state.update = true;
        this.state.index = index
    }
}
<ebay-carousel
    index=state.index
    on-scroll('onScroll')>...Items</>
 ```

## Workaround
 When state variables are replaced with local variables, they are working fine.

## Screenshots
![ebay-carousel-bug](https://user-images.githubusercontent.com/82911110/124803404-eab17780-df0d-11eb-9748-984610cd6b7d.gif)

**Comment by agliga** [comment] 2022-10-19 21:59
Closing, this is working fine and as intended.

**Closed by agliga** 2022-10-19 21:59 UTC
Labels: component: carousel, type: bug, status: backlog, priority: 3
