### ISSUE TITLE
ebay-carousel: last slide not returning to first slide correctly

### ISSUE THREAD

**Issue by mcferrenm** [eBay/ebayui-core#1113] opened 2020-05-06 21:34 UTC
# Bug Report

## Description

After navigating through carousel slides, the last jumps through a number of slides backwards.

No errors in the console.

Expected:
Cleanly slides to first slide without going backward.

## Screenshots

![carousel-issue](https://user-images.githubusercontent.com/10376398/81231268-b9ef4e80-8fa7-11ea-933e-f75d6505c960.gif)

**Comment by ianmcburnie** [comment] 2020-05-06 22:02
Yes, that is ugly. @mcferrenm Do you have any kind of temp workaround for now while we look into a fix?

**Comment by mcferrenm** [comment] 2020-05-06 22:49
@ianmcburnie This isn't in prod, so I haven't come up with a work around yet.

**Comment by agliga** [comment] 2020-05-11 18:27
On our demo page this works correctly https://ebay.github.io/ebayui-core/?path=/story/ebay-carousel--autoplay It transitions properly to the first slide.

**Comment by agliga** [comment] 2020-05-11 18:34
Closing for now. If you find an issue with the component based on this please feel free to reopen!

**Comment by agliga** [comment] 2020-05-18 17:55
Re opening. Was able to reproduce this on our code. 
Issue happens on autoplay carousel with `items-per-slide=1`. Not sure why this is the case, but was able to reproduce it.

**Comment by agliga** [comment] 2020-05-19 19:54
So this is how the issue happens:
On page load, if you start to interact with the carousel, it does not correctly transition to the first slide. However, if you click anywhere else on the page, it starts to work.
This is found to be related with `marko`, specifically `marko@4.20.1` It seems to be a race condition with `queueMicrotask`
Will update once we get a solution either in marko or ebayui

**Comment by agliga** [comment] 2020-05-20 21:00
Fixed issue in `marko@4.21.10`.

**Closed by agliga** 2020-05-20 21:00 UTC
Labels: aspect: marko, regression: yes, status: in progress, type: bug
