### ISSUE TITLE
common.dom.useReducedMotion: Causing test failures

### ISSUE THREAD

**Issue by aaron-nance** [eBay/ebayui-core#2338] opened 2024-12-10 22:41 UTC
# Bug Report

## Description

The `common.dom.useReducedMotion` call is causing test failures in several applcations, due to JSDOM not having an implementaion of `window.matchMedia`. This is preventing completion of the December SWU updates. 

## Workaround

The workaround is to add s mock for `window.matchMedia` to the affected application. This is undesireable since it adds tech debt to several applications.

**Comment by agliga** [comment] 2024-12-10 22:54
Closing
This is a supported browser feature in all modern browsers. 
We wont fix if a testing library does not support common browser features. 

That said there are workarounds https://stackoverflow.com/questions/39830580/jest-test-fails-typeerror-window-matchmedia-is-not-a-function
I would use those to get your tests to pass.

**Comment by LuLaValva** [comment] 2024-12-10 22:56
@agliga I've been working with @aaron-nance to get this feature in, we're going to add a null check. It has negligible cost and prevents teams from having to mock the feature.

**Comment by agliga** [comment] 2024-12-10 22:57
> @agliga I've been working with @aaron-nance to get this feature in, we're going to add a null check. It has negligible cost and prevents teams from having to mock the feature.

We shouldn't be adding null checks on built in browser features.

**Comment by aaron-nance** [comment] 2024-12-10 23:04
> > @agliga I've been working with @aaron-nance to get this feature in, we're going to add a null check. It has negligible cost and prevents teams from having to mock the feature.
> 
> We shouldn't be adding null checks on built in browser features.

Fixing an issue's root at the source saves a lot of time and money. Much time has been and is being lost across our applications due to having to diagnose and then seek out the fix for this.

**Comment by agliga** [comment] 2024-12-10 23:05
> > > @agliga I've been working with @aaron-nance to get this feature in, we're going to add a null check. It has negligible cost and prevents teams from having to mock the feature.
> 
> > 
> 
> > We shouldn't be adding null checks on built in browser features.
> 
> 
> 
> Fixing an issue's root at the source saves a lot of time and money. Much time has been and is being lost across our applications due to having to diagnose and then seek out the fix for this.

Yes the issue is with jest not having a supported browser feature. 
If this is supported by all browsers and jest is missing seems like that's the problem.

**Comment by LuLaValva** [comment] 2024-12-12 16:01
After some discussion offline, we've decided not to move forward with this fix. It sets a precedent that supported browser APIs should not be depended upon when older testing libraries don't support them, when really the root cause is from those testing libraries and not eBayUI.

Hopefully, the time spent solving testing issues will be incentive to have better mocking capabilities for limited testing libraries or switch to a browser-based testing library like vitest.

**Closed by LuLaValva** 2024-12-12 16:01 UTC
Labels: type: bug
