### ISSUE TITLE
Infotip overlay cuts off when infotip is placed near the edge of the window

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/ebayui-core#1088] opened 2020-03-25 22:27 UTC
# Bug Report

## Description
When the infotip is placed near the window, it cuts off the overlay. Ideally it should truncate the overlay. This is reproducible in storybook as well. Just keep adding content to push the icon near the edge of the window. 

## Workaround
None

## Screenshots
<img width="349" alt="Screen Shot 2020-03-25 at 3 26 03 PM" src="https://user-images.githubusercontent.com/5200733/77591352-f90c8900-6eac-11ea-8067-d012900e375c.png">

**Comment by ianmcburnie** [comment] 2020-04-02 16:27
Related ticket: #535

**Comment by ianmcburnie** [comment] 2020-07-02 04:38
Closing as duplicate of #535.

**Closed by ianmcburnie** 2020-07-02 04:38 UTC
Labels: component: infotip, priority: 3, type: bug
