### ISSUE TITLE
ebay-filter-menu-button : Support for input field as a ebay-filter-menu-button-item

### ISSUE THREAD

**Issue by abiclub23** [eBay/ebayui-core#1096] opened 2020-04-15 22:22 UTC
# Feature Request

## Description
Currently the filter menu  only supports  checkbox options. For the usecase below , we also need support for input fields.

## Screenshots
![image](https://user-images.githubusercontent.com/6979452/79394672-e970e500-7f2c-11ea-90fa-8103a93716af.png)

**Comment by ianmcburnie** [comment] 2020-04-15 23:26
I'm checking in with design system team, but I'm pretty sure this is going to be a no, as it is off-pattern. From a technical point of view also with ARIA, it's not possible to have inputs as part of an ARIA menu.

**Comment by agliga** [comment] 2020-04-15 23:39
I think part of what we could do is allow custom user markup in that component. Because they can probably create it any way they want. The issue is that it only accepts `filter-menu-item` tags

**Comment by ianmcburnie** [comment] 2020-04-16 17:11
Guidance from design system team:

"At some point this drop down needs to become a modal. Complex interactions and input should not be in a dropdown."

Closing ticket. @abiclub23 Feel free to reach out to design system team for further guidance.

**Closed by ianmcburnie** 2020-04-16 17:11 UTC
Labels: blocked: design
